# Generated by Django 6.0.2 on 2026-02-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
